In [ ]:
Passek
1/28/20
Logistic Regression

In [123]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
#import matplotlib.pyplot as plt 
#plt.rc("font", size=14)
from sklearn.linear_model import LogisticRegression
#from sklearn.model_selection import train_test_split
#import seaborn as sns
#sns.set(style="white")
#sns.set(style="whitegrid", color_codes=True)

In [124]:
#Upload Data
datafile_tr = "/Users/justinpassek/Downloads/data/train.csv"
train = pd.read_csv(datafile_tr, header=0)
print(train)

datafile_te = "/Users/justinpassek/Downloads/data/test.csv"
test = pd.read_csv(datafile_te, header=0)
print(test)

      age  cost_of_ad device_type gender  in_initial_launch_location  income  \
0      56    0.005737      iPhone      M                           0   62717
1      50    0.004733     desktop      F                           0   64328
2      54    0.004129      laptop      M                           0   83439
3      16    0.005117     Android      F                           0   30110
4      37    0.003635     desktop      M                           0   76565
...   ...         ...         ...    ...                         ...     ...
9995   41    0.004225     desktop      M                           0   64489
9996   50    0.004751       other      F                           0   88643
9997   60    0.003804       other      M                           0   87870
9998   18    0.003838      laptop      M                           0   56468
9999   33    0.005250      iPhone    NaN                           0   59935

      n_drivers  n_vehicles  prior_ins_tenure  outcome
0             2           1                 4        0
1             2           3                 2        0
2             1           3                 7        0
3             2           3                 0        0
4             2           1                 5        0
...         ...         ...               ...      ...
9995          2           3                 8        0
9996          1           3                 0        0
9997          2           2                 9        0
9998          2           2                 0        0
9999          2           1                 6        0

[10000 rows x 10 columns]
      age  cost_of_ad device_type gender  in_initial_launch_location  income  \
0      34    0.005134     Android      F                           1   40376
1      53    0.005223     desktop      F                           1   84511
2      46    0.004939      laptop      F                           0   79322
3      36    0.004924     Android      F                           0   63295
4      28    0.005146       other      F                           1   36170
...   ...         ...         ...    ...                         ...     ...
9995   50    0.005927      iPhone      M                           1   78899
9996   24    0.005138     Android      F                           1   26703
9997   40    0.006225      iPhone      F                           1   62402
9998   38    0.004601       other      F                           1   58663
9999   33    0.005171       other      F                           1   69500

      n_drivers  n_vehicles  prior_ins_tenure
0             1           3                 7
1             1           1                11
2             1           1                 4
3             1           2                 0
4             1           3                 3
...         ...         ...               ...
9995          2           3                14
9996          1           3                 2
9997          1           2                 3
9998          1           1                 9
9999          2           1                 1

[10000 rows x 9 columns]

In [ ]:
df.plot(kind="scatter", x="longitude", y="latitude", alpha=0.2)
plt.savefig('map1.png')

In [125]:
#Scale Continuous Features
from sklearn.preprocessing import StandardScaler 
sc_x = StandardScaler() 

scaled_features = train.copy()
col_names = ['cost_of_ad', 'income','prior_ins_tenure','age']
features = scaled_features[col_names]
scaler = StandardScaler().fit(features.values)
features = scaler.transform(features.values)
scaled_features[col_names] = features
train = scaled_features
print(train)

scaled_features = test.copy()
col_names = ['cost_of_ad', 'income','prior_ins_tenure','age']
features = scaled_features[col_names]
scaler = StandardScaler().fit(features.values)
features = scaler.transform(features.values)
scaled_features[col_names] = features
test = scaled_features
print(test)
#scaled_features_test = test.copy()

#train = sc_x.fit_transform(train)  
#test = sc_x.transform(test)

           age  cost_of_ad device_type gender  in_initial_launch_location  \
0     1.381256    1.277357      iPhone      M                           0
1     0.921047    0.079360     desktop      F                           0
2     1.227853   -0.640598      laptop      M                           0
3    -1.686805    0.538199     Android      F                           0
4    -0.076073   -1.230918     desktop      M                           0
...        ...         ...         ...    ...                         ...
9995  0.230734   -0.526948     desktop      M                           0
9996  0.921047    0.100794       other      F                           0
9997  1.688062   -1.028628       other      M                           0
9998 -1.533401   -0.988309      laptop      M                           0
9999 -0.382879    0.696865      iPhone    NaN                           0

        income  n_drivers  n_vehicles  prior_ins_tenure  outcome
0     0.271938          2           1         -0.278808        0
1     0.364899          2           3         -0.675180        0
2     1.467674          1           3          0.315750        0
3    -1.609606          2           3         -1.071553        0
4     1.071019          2           1         -0.080622        0
...        ...        ...         ...               ...      ...
9995  0.374189          2           3          0.513936        0
9996  1.767964          1           3         -1.071553        0
9997  1.723359          2           2          0.712122        0
9998 -0.088652          2           2         -1.071553        0
9999  0.111406          2           1          0.117564        0

[10000 rows x 10 columns]
           age  cost_of_ad device_type gender  in_initial_launch_location  \
0    -0.312431    0.557090     Android      F                           1
1     1.160862    0.664439     desktop      F                           1
2     0.618070    0.323719      laptop      F                           0
3    -0.157348    0.306167     Android      F                           0
4    -0.777682    0.572028       other      F                           1
...        ...         ...         ...    ...                         ...
9995  0.928237    1.506600      iPhone      M                           1
9996 -1.087849    0.562722     Android      F                           1
9997  0.152819    1.862959      iPhone      F                           1
9998 -0.002264   -0.080485       other      F                           1
9999 -0.389973    0.601929       other      F                           1

        income  n_drivers  n_vehicles  prior_ins_tenure
0    -1.031112          1           3          0.334752
1     1.517491          1           1          1.131686
2     1.217849          1           1         -0.262948
3     0.292360          1           2         -1.059882
4    -1.273990          1           3         -0.462182
...        ...        ...         ...               ...
9995  1.193423          2           3          1.729387
9996 -1.820668          1           3         -0.661415
9997  0.240793          1           2         -0.462182
9998  0.024882          1           1          0.733219
9999  0.650672          2           1         -0.860649

[10000 rows x 9 columns]

In [126]:
train.dtypes
train['in_initial_launch_location'] = train['in_initial_launch_location'].astype(object)
train['n_drivers'] = train['n_drivers'].astype(object)
train['n_vehicles'] = train['n_vehicles'].astype(object)
#train['age'] = train['age'].astype(object)

test['in_initial_launch_location'] = test['in_initial_launch_location'].astype(object)
test['n_drivers'] = test['n_drivers'].astype(object)
test['n_vehicles'] = test['n_vehicles'].astype(object)
#test['age'] = test['age'].astype(object)

In [127]:
# One-hot encode categorical features
# label encoding the data 

def encode_and_bind(original_dataframe, feature_to_encode):
    dummies = pd.get_dummies(original_dataframe[[feature_to_encode]])
    res = pd.concat([original_dataframe, dummies], axis=1)
    res = res.drop([feature_to_encode], axis=1)
    return(res) 

train = encode_and_bind(train, 'gender')
train = encode_and_bind(train, 'device_type')
train = encode_and_bind(train, 'in_initial_launch_location')
train = encode_and_bind(train, 'n_drivers')
train = encode_and_bind(train, 'n_vehicles')
#train = encode_and_bind(train, 'age')

print(train)

test = encode_and_bind(test, 'gender')
test = encode_and_bind(test, 'device_type')
test = encode_and_bind(test, 'in_initial_launch_location')
test = encode_and_bind(test, 'n_drivers')
test = encode_and_bind(test, 'n_vehicles')
#test = encode_and_bind(test, 'age')

print(test)

           age  cost_of_ad    income  prior_ins_tenure  outcome  gender_F  \
0     1.381256    1.277357  0.271938         -0.278808        0         0
1     0.921047    0.079360  0.364899         -0.675180        0         1
2     1.227853   -0.640598  1.467674          0.315750        0         0
3    -1.686805    0.538199 -1.609606         -1.071553        0         1
4    -0.076073   -1.230918  1.071019         -0.080622        0         0
...        ...         ...       ...               ...      ...       ...
9995  0.230734   -0.526948  0.374189          0.513936        0         0
9996  0.921047    0.100794  1.767964         -1.071553        0         1
9997  1.688062   -1.028628  1.723359          0.712122        0         0
9998 -1.533401   -0.988309 -0.088652         -1.071553        0         0
9999 -0.382879    0.696865  0.111406          0.117564        0         0

      gender_M  device_type_Android  device_type_desktop  device_type_iPhone  \
0            1                    0                    0                   1
1            0                    0                    1                   0
2            1                    0                    0                   0
3            0                    1                    0                   0
4            1                    0                    1                   0
...        ...                  ...                  ...                 ...
9995         1                    0                    1                   0
9996         0                    0                    0                   0
9997         1                    0                    0                   0
9998         1                    0                    0                   0
9999         0                    0                    0                   1

      device_type_laptop  device_type_other  in_initial_launch_location_0  \
0                      0                  0                             1
1                      0                  0                             1
2                      1                  0                             1
3                      0                  0                             1
4                      0                  0                             1
...                  ...                ...                           ...
9995                   0                  0                             1
9996                   0                  1                             1
9997                   0                  1                             1
9998                   1                  0                             1
9999                   0                  0                             1

      in_initial_launch_location_1  n_drivers_1  n_drivers_2  n_vehicles_1  \
0                                0            0            1             1
1                                0            0            1             0
2                                0            1            0             0
3                                0            0            1             0
4                                0            0            1             1
...                            ...          ...          ...           ...
9995                             0            0            1             0
9996                             0            1            0             0
9997                             0            0            1             0
9998                             0            0            1             0
9999                             0            0            1             1

      n_vehicles_2  n_vehicles_3
0                0             0
1                0             1
2                0             1
3                0             1
4                0             0
...            ...           ...
9995             0             1
9996             0             1
9997             1             0
9998             1             0
9999             0             0

[10000 rows x 19 columns]
           age  cost_of_ad    income  prior_ins_tenure  gender_F  gender_M  \
0    -0.312431    0.557090 -1.031112          0.334752         1         0
1     1.160862    0.664439  1.517491          1.131686         1         0
2     0.618070    0.323719  1.217849         -0.262948         1         0
3    -0.157348    0.306167  0.292360         -1.059882         1         0
4    -0.777682    0.572028 -1.273990         -0.462182         1         0
...        ...         ...       ...               ...       ...       ...
9995  0.928237    1.506600  1.193423          1.729387         0         1
9996 -1.087849    0.562722 -1.820668         -0.661415         1         0
9997  0.152819    1.862959  0.240793         -0.462182         1         0
9998 -0.002264   -0.080485  0.024882          0.733219         1         0
9999 -0.389973    0.601929  0.650672         -0.860649         1         0

      device_type_Android  device_type_desktop  device_type_iPhone  \
0                       1                    0                   0
1                       0                    1                   0
2                       0                    0                   0
3                       1                    0                   0
4                       0                    0                   0
...                   ...                  ...                 ...
9995                    0                    0                   1
9996                    1                    0                   0
9997                    0                    0                   1
9998                    0                    0                   0
9999                    0                    0                   0

      device_type_laptop  device_type_other  in_initial_launch_location_0  \
0                      0                  0                             0
1                      0                  0                             0
2                      1                  0                             1
3                      0                  0                             1
4                      0                  1                             0
...                  ...                ...                           ...
9995                   0                  0                             0
9996                   0                  0                             0
9997                   0                  0                             0
9998                   0                  1                             0
9999                   0                  1                             0

      in_initial_launch_location_1  n_drivers_1  n_drivers_2  n_vehicles_1  \
0                                1            1            0             0
1                                1            1            0             1
2                                0            1            0             1
3                                0            1            0             0
4                                1            1            0             0
...                            ...          ...          ...           ...
9995                             1            0            1             0
9996                             1            1            0             0
9997                             1            1            0             0
9998                             1            1            0             1
9999                             1            0            1             1

      n_vehicles_2  n_vehicles_3
0                0             1
1                0             0
2                0             0
3                1             0
4                0             1
...            ...           ...
9995             0             1
9996             0             1
9997             1             0
9998             0             0
9999             0             0

[10000 rows x 18 columns]

In [128]:
# Split data into 'X' features and 'y' target label sets
X_train = train.drop('outcome', 1)
y_train = train['outcome']

X_test  = train.drop('outcome', 1)
y_test  = train['outcome']

In [136]:
# Import module for fitting
from sklearn.linear_model import LogisticRegression
# Create instance (i.e. object) of LogisticRegression
logmodel = LogisticRegression(class_weight='balanced',solver='liblinear',max_iter=10000,penalty='l2')
# Fit the model using the training data
# X_train -> parameter supplies the data features
# y_train -> parameter supplies the target labels
logmodel.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight='balanced', dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=10000,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

In [137]:
# check the accuracy on the training set
from sklearn.metrics import accuracy_score  
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import roc_auc_score
from sklearn.metrics import classification_report

#logmodel.score(X_train, y_train)

score = accuracy_score(y_test, logmodel.predict(X_test))
roc   = roc_auc_score(y_test, logmodel.predict(X_test))
cr    = classification_report(y_test, logmodel.predict(X_test))

print(score)
print(roc)
print(cr)

0.7373
0.7450002687541867
             precision    recall  f1-score   support

          0       0.96      0.74      0.83      9018
          1       0.24      0.75      0.36       982

avg / total       0.89      0.74      0.79     10000

In [135]:
from sklearn.metrics import confusion_matrix
predicted = logmodel.predict(X_test)
matrix = confusion_matrix(y_test, predicted)
print(matrix)

[[8973   45]
 [ 866  116]]

In [142]:
coef = logmodel.coef_[0]
print (coef)
print(logmodel.coef_, logmodel.intercept_)

[-0.23858041  0.6499109   0.11904854 -0.13469372 -0.53394664  1.31318723
  0.79978954  1.16069692 -1.15655856 -0.41535751 -0.80148784 -0.63420655
  0.2212891  -0.53770291  0.12478546  0.96495519 -0.31931098 -1.05856166]
[[-0.23858041  0.6499109   0.11904854 -0.13469372 -0.53394664  1.31318723
   0.79978954  1.16069692 -1.15655856 -0.41535751 -0.80148784 -0.63420655
   0.2212891  -0.53770291  0.12478546  0.96495519 -0.31931098 -1.05856166]] [-0.41291745]